# Generated by Django 4.2.6 on 2026-03-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('club_name', models.CharField(max_length=20)),
            ],
        ),
    ]
