# Generated by Django 4.2.6 on 2026-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzy', '0003_state_district_postoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
