# Generated by Django 4.2.6 on 2026-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzy', '0006_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='post_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
