# Generated by Django 4.2.6 on 2026-05-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportzy', '0007_alter_player_post_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_master_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
