# Generated by Django 4.2.6 on 2026-05-25 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportzy', '0009_clubprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball')], max_length=50)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('second_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('third_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('mvp_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('squad_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('match_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('overs', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('set_format', models.CharField(blank=True, max_length=100, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
