# Generated by Django 5.0.4 on 2026-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzy', '0010_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
